# Generated by Django 4.1.1 on 2022-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tournament date'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
