# Generated by Django 4.1.1 on 2022-09-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_player_bracket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.bracket'),
        ),
    ]
