# Generated by Django 4.1.1 on 2022-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounds',
            name='players',
        ),
        migrations.AddField(
            model_name='rounds',
            name='player1_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rounds',
            name='player2_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
