# Generated by Django 4.1.5 on 2023-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0006_remove_rounds_players_rounds_player1_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="score_round",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="rounds",
            name="player1_score",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="rounds",
            name="player2_score",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
