# Generated by Django 4.1.5 on 2023-05-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0007_player_score_round_rounds_player1_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracket",
            name="numberOfRounds",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="rounds",
            name="isFinished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="score",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="score_round",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="rounds",
            name="player1_score",
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="rounds",
            name="player2_score",
            field=models.FloatField(default=0, null=True),
        ),
    ]
